/**
 * ============================================================================
 * The typed API client — the single way the UI talks to the backend.
 * ============================================================================
 *
 * This wraps the client generated by `@hey-api/openapi-ts` from the committed
 * `openapi/openapi.json` contract (re-exported below), so every request and
 * response shape is compile-time checked against the running backend.
 *
 * Four responsibilities beyond the generated calls:
 *
 *   1. BASE URL `/api/v1` — a SAME-ORIGIN relative path. The Caddy proxy fronts
 *      the UI, the API and the IdP under one TLS origin, so there is no CORS
 *      surface and no cross-origin cookie problem, and nothing internal
 *      (`minio:9000`, `api:3000`) is ever referenced from the browser.
 *   2. The session bearer token is attached to every call from a pluggable
 *      provider — `AuthProvider` registers the real one at startup.
 *   3. A 401 clears the session and redirects to login. Plan 01-06 revokes
 *      sessions on ANY role or scope change, so a mid-session 401 is an
 *      expected, routine event, not an error — the user simply signs in again.
 *   4. A non-2xx body is surfaced as {@link ApiError}, carrying the stable
 *      `error_code` from `FRD/Y2-errors.md` so screens branch on the code, not
 *      on message text.
 */
import { client as generatedClient } from './generated';
import type { ApiErrorBody } from './generated/types.gen';

export * from './generated';

/** Same-origin API prefix. The Caddy proxy fronts the API at this path. */
const API_BASE_URL = '/api/v1';

/**
 * A non-2xx response surfaced as a typed error.
 *
 * Carries the FRD Y2 envelope's stable `error_code` plus the HTTP status, so a
 * screen can branch on, e.g., `AUTH_SCOPE_DENIED` vs `CASE_DESIGNATION_DENIED`
 * without parsing a human-readable (and translatable, and changeable) message.
 */
export class ApiError extends Error {
  readonly error_code: string;
  readonly status: number;
  readonly detail?: unknown;

  constructor(error_code: string, message: string, status: number, detail?: unknown) {
    super(message);
    this.name = 'ApiError';
    this.error_code = error_code;
    this.status = status;
    this.detail = detail;
  }
}

/**
 * The session-token source. `AuthProvider` installs the real getter at startup
 * via {@link setSessionTokenProvider}; until then there is no token and calls
 * go out unauthenticated (correct for `GET /auth/authorize-url`).
 */
let getSessionToken: () => string | null = () => null;

/** Called by `AuthProvider` once logout/clear is wired. */
let onUnauthenticated: () => void = () => {
  // Default: a hard redirect to the login route. `AuthProvider` replaces this
  // with a session-clearing variant that preserves the intended path.
  if (typeof window !== 'undefined' && window.location.pathname !== '/login') {
    window.location.assign('/login');
  }
};

/** Register the function that returns the current session bearer token. */
export function setSessionTokenProvider(provider: () => string | null): void {
  getSessionToken = provider;
}

/** Register what to do when the server reports the session is no longer valid. */
export function setUnauthenticatedHandler(handler: () => void): void {
  onUnauthenticated = handler;
}

/**
 * Configure the generated client once at module load: same-origin base URL,
 * a request interceptor that attaches the bearer token, and a response
 * interceptor that turns a 401 into a session clear + login redirect and any
 * other non-2xx into an {@link ApiError}.
 */
generatedClient.setConfig({ baseUrl: API_BASE_URL });

generatedClient.interceptors.request.use((request) => {
  const token = getSessionToken();
  if (token !== null && token !== '') {
    request.headers.set('Authorization', `Bearer ${token}`);
  }
  return request;
});

generatedClient.interceptors.response.use(async (response) => {
  if (response.ok) {
    return response;
  }

  if (response.status === 401) {
    // Routine, not exceptional: the server revoked the session (role/scope
    // change, expiry). Stop showing stale state and send the user to sign in.
    onUnauthenticated();
  }

  // Surface a typed, code-branchable error. The body is the FRD Y2 envelope on
  // every deliberate failure; fall back gracefully if a response is malformed.
  let body: Partial<ApiErrorBody> = {};
  try {
    body = (await response.clone().json()) as Partial<ApiErrorBody>;
  } catch {
    // Non-JSON error body (e.g. a proxy 502). Leave the defaults.
  }

  throw new ApiError(
    body.error_code ?? 'UNKNOWN_ERROR',
    body.message ?? `Request failed with status ${response.status}`,
    response.status,
    body.detail,
  );
});

/** The configured generated client, for callers that want the singleton. */
export const api = generatedClient;
